### ISSUE TITLE
Centos 6 LXC/Proxmox

### ISSUE THREAD

**Issue by arquio** [gecos-team/gecos-doc#1]
Hi gecos-team,

We have found an error during the install-script executation. 

Environment:  Centos 6 LXC/Proxmox (From centos-6-default_20160205_amd64.tar.xz)

Thanks u!

> .......
> Installing ffi-yajl 1.4.0 with native extensions
> **An error occurred while installing rack (2.0.1), and Bundler cannot continue.**
> Make sure that `gem install rack -v '2.0.1'` succeeds before bundling.
> Submodule 'cookbooks/chef-client' (https://github.com/opscode-cookbooks/chef-client.git) registered for path 'cookbooks/chef-client'
> ...
> [gecos-install.txt](https://github.com/gecos-team/gecos-doc/files/413603/gecos-install.txt)

**Comment by arquio** [comment]
> ERROR:  Error installing rack:
>   **rack requires Ruby version >= 2.2.2.**
> [root@gecos ~]# ruby --version
> ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]

**Comment by alfem** [comment]
Try the brand new installer: 

https://github.com/gecos-team/gecoscc-installer
